import { createHash } from 'node:crypto'
import { readdir, readFile } from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import pg from 'pg'

/**
 * Migration runner.
 *
 * Applies every .sql file in drizzle/ in filename order, whether generated by
 * drizzle-kit or hand-written. The RLS and privilege migration is hand-written
 * because it is the security boundary, so the runner must treat both kinds
 * identically rather than relying on drizzle-kit's journal.
 *
 * Runs as MIGRATION_DATABASE_URL - the privileged role that owns the schema.
 * It is never the role that serves requests.
 */

const MIGRATIONS_DIR = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  '../../../drizzle',
)

const SEPARATOR = '--> statement-breakpoint'

/**
 * True when a chunk contains nothing but SQL comments and blank lines.
 *
 * Deliberately line-based rather than a regex: a pattern like
 * /^(--[^\n]*\n?)+$/ backtracks catastrophically against a long comment
 * header followed by real SQL, which is exactly the shape of the RLS
 * migration. This runs in linear time.
 */
function isCommentOnly(chunk: string): boolean {
  return chunk.split('\n').every((line) => line.trim() === '' || line.trimStart().startsWith('--'))
}

export interface MigrationResult {
  applied: string[]
  skipped: string[]
}

export async function runMigrations(connectionString: string): Promise<MigrationResult> {
  const client = new pg.Client({
    connectionString,
    ssl: /\bsslmode=require\b/.test(connectionString) ? { rejectUnauthorized: true } : undefined,
  })
  await client.connect()

  const applied: string[] = []
  const skipped: string[] = []

  try {
    await client.query(`
      create table if not exists evercalm_migrations (
        filename   text primary key,
        checksum   text not null,
        applied_at timestamptz not null default now()
      )
    `)

    const files = (await readdir(MIGRATIONS_DIR))
      .filter((f) => f.endsWith('.sql'))
      .sort((a, b) => a.localeCompare(b))

    const existing = await client.query<{ filename: string; checksum: string }>(
      'select filename, checksum from evercalm_migrations',
    )
    const seen = new Map(existing.rows.map((r) => [r.filename, r.checksum]))

    for (const file of files) {
      const sqlText = await readFile(path.join(MIGRATIONS_DIR, file), 'utf8')
      const checksum = createHash('sha256').update(sqlText).digest('hex')

      const prior = seen.get(file)
      if (prior) {
        if (prior !== checksum) {
          throw new Error(
            `Migration ${file} was modified after being applied ` +
              `(recorded ${prior.slice(0, 12)}, now ${checksum.slice(0, 12)}). ` +
              `Applied migrations are immutable - add a new migration instead.`,
          )
        }
        skipped.push(file)
        continue
      }

      const statements = sqlText
        .split(SEPARATOR)
        .map((s) => s.trim())
        .filter((s) => s.length > 0 && !isCommentOnly(s))

      await client.query('begin')
      try {
        for (const statement of statements) {
          await client.query(statement)
        }
        await client.query('insert into evercalm_migrations (filename, checksum) values ($1, $2)', [
          file,
          checksum,
        ])
        await client.query('commit')
        applied.push(file)
      } catch (error) {
        await client.query('rollback')
        const message = error instanceof Error ? error.message : String(error)
        throw new Error(`Migration ${file} failed: ${message}`)
      }
    }
  } finally {
    await client.end()
  }

  return { applied, skipped }
}

// CLI entrypoint: npm run db:migrate
const isDirectRun =
  process.argv[1] !== undefined && fileURLToPath(import.meta.url) === path.resolve(process.argv[1])

if (isDirectRun) {
  const { config } = await import('dotenv')
  config({ path: '.env.local', quiet: true })
  config({ quiet: true })

  const url = process.env.MIGRATION_DATABASE_URL
  if (!url) {
    console.error(
      'MIGRATION_DATABASE_URL is not set.\n' +
        'Migrations must run as the privileged migration role, never as the application runtime role.\n' +
        'See docs/database-setup.md.',
    )
    process.exit(1)
  }
  const result = await runMigrations(url)
  for (const f of result.skipped) console.log(`  = ${f} (already applied)`)
  for (const f of result.applied) console.log(`  + ${f}`)
  console.log(
    result.applied.length === 0
      ? 'Database is up to date.'
      : `Applied ${result.applied.length} migration(s).`,
  )
}
