import { and, eq, gt, lt } from 'drizzle-orm'
import type { NodePgDatabase } from 'drizzle-orm/node-postgres'
import { newId } from '@/lib/ids'
import type { Tx } from '@/server/db/types'
import { generateForUpcomingShifts } from '@/modules/operations/generation'
import {
  localDateOf,
  localTimeToInstant,
  parseTimeOfDay,
  weekStartOf,
} from '@/modules/scheduling/time'
import * as schema from '../full-schema'

/*
 * SHIFT OPERATIONS DEMO DATA.
 *
 * Published templates in each business's own words, then a real day of work:
 *
 *   Harbor & Vine   pre-shift lineup (uniform check, the 86 list, reservations
 *                   and large parties, manager notes), server side work, bar
 *                   setup and an overnight bar close, host stand setup
 *                   Downtown, and the closing handoff.
 *   Lumen Salon     appointment review and client notes at the desk, station
 *                   setup and sanitation, a product inventory count, closing
 *                   duties, the next-day handoff, and treatment-room turnover
 *                   in Boise, an hour ahead.
 *
 * Today's demo shifts are placed around the moment the seed runs, so there is
 * always a shift on now with finished, waiting, blocked, skipped and sent-back
 * work to look at. Work is generated by the SAME code a published schedule
 * uses; only the states people have already reached are written here.
 */

type SeedDb = NodePgDatabase<typeof schema>

interface TaskSeed {
  title: string
  instructions?: string
  optional?: boolean
  response?: 'check' | 'text' | 'number' | 'handoff'
  /** Minutes from the start (`start`) or the end (`end`) of the shift. */
  at: [anchor: 'start' | 'end', minutes: number]
  verify?: boolean
  shared?: boolean
}

interface TemplateSeed {
  name: string
  kind:
    'pre_shift' | 'opening' | 'side_work' | 'station_setup' | 'shift_duties' | 'closing' | 'handoff'
  description?: string
  locations: string[]
  jobRoles?: string[]
  stations?: { location: string; name: string }[]
  author: string
  sections: { title: string; tasks: TaskSeed[] }[]
}

interface DemoShift {
  key: string
  person: string
  location: string
  jobRole: string
  station?: string
  /** 'now': starts two hours before the seed runs. Otherwise a local clock time today. */
  start: string
  minutes: number
}

type ItemPatch =
  | { status: 'done'; by?: string; text?: string; number?: string; verifiedBy?: string }
  | { status: 'awaiting_verification'; by?: string; text?: string; number?: string }
  | { status: 'skipped'; by?: string; reason: string }
  | { status: 'blocked'; reason: string }
  | { status: 'pending'; returnedNote: string; returnedBy: string }

interface OperationsSeed {
  templates: TemplateSeed[]
  shifts: DemoShift[]
  states: { shift: string; template: string; task: string; patch: ItemPatch }[]
  handoffs: {
    location: string
    author: string
    shift?: string
    hoursAgo: number
    category: 'staffing' | 'inventory' | 'maintenance' | 'safety' | 'guest' | 'follow_up'
    urgent?: boolean
    title: string
    body: string
    resolved?: { by: string; note: string; hoursAgo: number }
    readBy?: string[]
  }[]
}

// ---------------------------------------------------------------------------
// Harbor & Vine
// ---------------------------------------------------------------------------

const HARBOR: OperationsSeed = {
  templates: [
    {
      name: 'Pre-shift lineup',
      kind: 'pre_shift',
      description: 'Everything front of house needs before the first table.',
      locations: ['riverside'],
      jobRoles: ['server', 'bartender'],
      author: 'gm-riverside',
      sections: [
        {
          title: 'Before lineup',
          tasks: [
            {
              title: 'Uniform check',
              instructions:
                'Black shirt pressed, apron clean, name badge on, non-slip closed-toe shoes.',
              at: ['start', -15],
              verify: true,
            },
            {
              title: 'Read tonight’s 86 list',
              instructions:
                'Know what is out before you greet a table. The list is on the pass and in Messages.',
              at: ['start', -10],
            },
            {
              title: 'Review reservations and large parties',
              instructions:
                'Parties of 8 or more in your section, allergies flagged on the book, anyone celebrating.',
              response: 'text',
              at: ['start', -10],
            },
            {
              title: 'Manager notes at lineup',
              instructions:
                'Specials, pacing for the large party, and anything from last night’s handoff.',
              at: ['start', 0],
            },
          ],
        },
      ],
    },
    {
      name: 'Server side work',
      kind: 'side_work',
      locations: ['riverside'],
      jobRoles: ['server'],
      author: 'gm-riverside',
      sections: [
        {
          title: 'Opening side work',
          tasks: [
            { title: 'Polish and set glassware', at: ['start', 0], shared: true },
            {
              title: 'Fill salt, pepper and sugar caddies',
              at: ['start', 15],
              shared: true,
              optional: true,
            },
            {
              title: 'Stock the server station: napkins, check presenters, pens',
              at: ['start', 15],
            },
          ],
        },
        {
          title: 'Before close',
          tasks: [
            { title: 'Roll silverware for tomorrow (100 sets)', at: ['end', -90] },
            { title: 'Wipe down and sanitize menus', at: ['end', -60], shared: true },
          ],
        },
      ],
    },
    {
      name: 'Bar station setup',
      kind: 'station_setup',
      locations: ['riverside'],
      jobRoles: ['bartender'],
      stations: [{ location: 'riverside', name: 'Bar' }],
      author: 'gm-riverside',
      sections: [
        {
          title: 'Bar',
          tasks: [
            {
              title: 'Count the opening till',
              response: 'number',
              at: ['start', -15],
              verify: true,
            },
            { title: 'Cut garnish: lemons, limes, oranges', at: ['start', 0] },
            { title: 'Ice the wells', at: ['start', 15] },
          ],
        },
      ],
    },
    {
      name: 'Bar close',
      kind: 'closing',
      locations: ['riverside'],
      jobRoles: ['bartender'],
      author: 'gm-riverside',
      sections: [
        {
          title: 'Last hour',
          tasks: [
            { title: 'Last call at 12:30', at: ['end', -30] },
            { title: 'Log the walk-in temperature (°F)', response: 'number', at: ['end', -15] },
            { title: 'Clean and sanitize bar mats and speed rails', at: ['end', 0] },
            {
              title: 'Count the till with the closing manager',
              response: 'number',
              at: ['end', 0],
              verify: true,
            },
          ],
        },
      ],
    },
    {
      name: 'Closing handoff',
      kind: 'handoff',
      locations: ['riverside'],
      jobRoles: ['server', 'bartender'],
      author: 'gm-riverside',
      sections: [
        {
          title: 'Before you leave',
          tasks: [
            {
              title: 'Leave a handoff for tomorrow’s opener',
              instructions:
                'Anything they walk into: low stock, a guest coming back, equipment acting up.',
              response: 'handoff',
              at: ['end', 0],
            },
          ],
        },
      ],
    },
    {
      name: 'Host stand setup',
      kind: 'station_setup',
      locations: ['downtown'],
      jobRoles: ['host'],
      author: 'gm-downtown',
      sections: [
        {
          title: 'Host stand',
          tasks: [
            { title: 'Print the reservation sheet and flag large parties', at: ['start', -15] },
            { title: 'Wipe and sanitize menus', at: ['start', 0] },
            { title: 'Charge the waitlist tablet', at: ['start', 0] },
          ],
        },
      ],
    },
  ],
  shifts: [
    {
      key: 'sam',
      person: 'server',
      location: 'riverside',
      jobRole: 'server',
      station: 'Server Station B',
      start: 'now',
      minutes: 390,
    },
    {
      key: 'ava',
      person: 'new-server',
      location: 'riverside',
      jobRole: 'server',
      station: 'Server Station A',
      start: 'now',
      minutes: 390,
    },
    {
      key: 'camille',
      person: 'bartender',
      location: 'riverside',
      jobRole: 'bartender',
      station: 'Bar',
      start: '17:00',
      minutes: 480,
    },
    {
      key: 'theo',
      person: 'host',
      location: 'downtown',
      jobRole: 'host',
      station: 'Host Stand',
      start: '16:30',
      minutes: 330,
    },
  ],
  states: [
    {
      shift: 'sam',
      template: 'Pre-shift lineup',
      task: 'Uniform check',
      patch: { status: 'awaiting_verification' },
    },
    {
      shift: 'sam',
      template: 'Pre-shift lineup',
      task: 'Read tonight’s 86 list',
      patch: { status: 'done' },
    },
    {
      shift: 'sam',
      template: 'Pre-shift lineup',
      task: 'Review reservations and large parties',
      patch: {
        status: 'done',
        text: 'Party of 12 at 7:30 in my section. Two nut allergies on the booking.',
      },
    },
    {
      shift: 'sam',
      template: 'Pre-shift lineup',
      task: 'Manager notes at lineup',
      patch: { status: 'done' },
    },
    {
      shift: 'sam',
      template: 'Server side work',
      task: 'Polish and set glassware',
      patch: { status: 'done', by: 'new-server' },
    },
    {
      shift: 'sam',
      template: 'Server side work',
      task: 'Fill salt, pepper and sugar caddies',
      patch: {
        status: 'skipped',
        reason: 'Caddies are in the dish pit. Refilling after the first turn.',
      },
    },
    {
      shift: 'sam',
      template: 'Server side work',
      task: 'Stock the server station: napkins, check presenters, pens',
      patch: {
        status: 'blocked',
        reason: 'Out of check presenters. Asked Jordan to bring some from Downtown.',
      },
    },
    {
      shift: 'ava',
      template: 'Pre-shift lineup',
      task: 'Read tonight’s 86 list',
      patch: { status: 'done' },
    },
    {
      shift: 'ava',
      template: 'Pre-shift lineup',
      task: 'Uniform check',
      patch: {
        status: 'pending',
        returnedNote: 'Apron has a stain. Swap it before you greet tables.',
        returnedBy: 'lead-riverside',
      },
    },
  ],
  handoffs: [
    {
      location: 'riverside',
      author: 'bartender',
      hoursAgo: 15,
      category: 'inventory',
      urgent: true,
      title: 'Down to two bottles of Tito’s',
      body: 'Order is in, delivery Thursday. Use the well vodka for rail drinks until then.',
      readBy: ['new-server'],
    },
    {
      location: 'riverside',
      author: 'lead-riverside',
      hoursAgo: 14,
      category: 'maintenance',
      title: 'Dish machine rinse arm is leaking',
      body: 'Towel is under it. The technician is booked for 10 AM.',
    },
    {
      location: 'riverside',
      author: 'server',
      shift: 'sam',
      hoursAgo: 1,
      category: 'guest',
      title: 'Guest coming back for a scarf left at table 14',
      body: 'It is in the office lost and found. Reservation name: Patel.',
    },
    {
      location: 'riverside',
      author: 'gm-riverside',
      hoursAgo: 30,
      category: 'staffing',
      title: 'Need a second host for Friday’s large party',
      body: 'Party of 30 at 7 PM.',
      resolved: { by: 'gm-riverside', note: 'Theo is covering from Downtown.', hoursAgo: 20 },
    },
  ],
}

// ---------------------------------------------------------------------------
// Lumen Salon & Spa
// ---------------------------------------------------------------------------

const LUMEN: OperationsSeed = {
  templates: [
    {
      name: 'Opening: appointment review',
      kind: 'opening',
      locations: ['pearl'],
      jobRoles: ['coordinator'],
      author: 'gm-pearl',
      sections: [
        {
          title: 'Front desk',
          tasks: [
            {
              title: 'Review today’s appointments and confirm the first three clients',
              at: ['start', 0],
            },
            {
              title: 'Flag client notes for today',
              instructions:
                'Allergies, patch tests due before colour, and saved formulas the colourist needs.',
              response: 'text',
              at: ['start', 15],
            },
            {
              title: 'Text clients booked before 11 about street parking',
              at: ['start', 30],
              optional: true,
            },
          ],
        },
      ],
    },
    {
      name: 'Station setup and sanitation',
      kind: 'station_setup',
      locations: ['pearl'],
      jobRoles: ['stylist', 'apprentice', 'colourist'],
      author: 'gm-pearl',
      sections: [
        {
          title: 'Your station',
          tasks: [
            {
              title: 'Sanitize chair, cape and tools; fresh Barbicide',
              instructions:
                'Clippers and combs fully submerged for ten minutes. Wipe the chair arms and headrest.',
              at: ['start', -15],
            },
            {
              title: 'Set out clean towels at the shampoo bowls',
              at: ['start', -10],
              shared: true,
            },
            { title: 'Check your station’s product is stocked', at: ['start', 0] },
          ],
        },
      ],
    },
    {
      name: 'Product inventory count',
      kind: 'shift_duties',
      locations: ['pearl'],
      jobRoles: ['coordinator'],
      author: 'gm-pearl',
      sections: [
        {
          title: 'Retail and backbar',
          tasks: [
            {
              title: 'Count retail shampoo and conditioner',
              response: 'number',
              at: ['start', 60],
              verify: true,
            },
            { title: 'Count colour tubes below par', response: 'number', at: ['end', -60] },
          ],
        },
      ],
    },
    {
      name: 'Closing duties',
      kind: 'closing',
      locations: ['pearl'],
      jobRoles: ['coordinator'],
      author: 'gm-pearl',
      sections: [
        {
          title: 'Close the salon',
          tasks: [
            { title: 'Wash and fold towels; start the dryer', at: ['end', -30], shared: true },
            { title: 'Wipe down the shampoo bowls and colour bar', at: ['end', -15], shared: true },
            {
              title: 'Run the end-of-day report and count the till',
              response: 'number',
              at: ['end', 0],
              verify: true,
            },
            { title: 'Lock the retail cabinet', at: ['end', 0] },
          ],
        },
      ],
    },
    {
      name: 'Next-day handoff',
      kind: 'handoff',
      locations: ['pearl'],
      jobRoles: ['coordinator', 'stylist'],
      author: 'gm-pearl',
      sections: [
        {
          title: 'For tomorrow',
          tasks: [
            {
              title: 'Leave notes for tomorrow’s opener',
              instructions:
                'Client follow-ups, product running low, anything that needs a call first thing.',
              response: 'handoff',
              at: ['end', 0],
            },
          ],
        },
      ],
    },
    {
      name: 'Treatment room turnover',
      kind: 'station_setup',
      locations: ['bench'],
      jobRoles: ['massage', 'esthetician'],
      author: 'gm-bench',
      sections: [
        {
          title: 'Between clients',
          tasks: [
            { title: 'Strip and sanitize the table; fresh linens', at: ['start', -10] },
            {
              title: 'Note room temperature and oils restocked',
              response: 'text',
              at: ['start', 0],
            },
          ],
        },
      ],
    },
  ],
  shifts: [
    {
      key: 'marisol',
      person: 'stylist-senior',
      location: 'pearl',
      jobRole: 'stylist',
      station: 'Chair 1',
      start: 'now',
      minutes: 480,
    },
    {
      key: 'tomas',
      person: 'apprentice',
      location: 'pearl',
      jobRole: 'apprentice',
      station: 'Shampoo Area',
      start: 'now',
      minutes: 360,
    },
    {
      key: 'riley',
      person: 'coordinator',
      location: 'pearl',
      jobRole: 'coordinator',
      station: 'Front Desk',
      start: 'now',
      minutes: 480,
    },
    {
      key: 'ruben',
      person: 'massage',
      location: 'bench',
      jobRole: 'massage',
      station: 'Treatment Room',
      start: '10:00',
      minutes: 480,
    },
  ],
  states: [
    {
      shift: 'riley',
      template: 'Opening: appointment review',
      task: 'Review today’s appointments and confirm the first three clients',
      patch: { status: 'done' },
    },
    {
      shift: 'riley',
      template: 'Opening: appointment review',
      task: 'Flag client notes for today',
      patch: {
        status: 'done',
        text: 'Mrs. Lindgren needs a patch test before Thursday’s colour. Jae: sensitive scalp, fragrance-free products only.',
      },
    },
    {
      shift: 'riley',
      template: 'Product inventory count',
      task: 'Count retail shampoo and conditioner',
      patch: { status: 'awaiting_verification', number: '14' },
    },
    {
      shift: 'marisol',
      template: 'Station setup and sanitation',
      task: 'Sanitize chair, cape and tools; fresh Barbicide',
      patch: {
        status: 'blocked',
        reason: 'Barbicide concentrate is out. Using disinfectant wipes until the order arrives.',
      },
    },
    {
      shift: 'marisol',
      template: 'Station setup and sanitation',
      task: 'Set out clean towels at the shampoo bowls',
      patch: { status: 'done', by: 'apprentice' },
    },
    {
      shift: 'marisol',
      template: 'Station setup and sanitation',
      task: 'Check your station’s product is stocked',
      patch: { status: 'done' },
    },
    {
      shift: 'tomas',
      template: 'Station setup and sanitation',
      task: 'Sanitize chair, cape and tools; fresh Barbicide',
      patch: { status: 'done', verifiedBy: 'gm-pearl' },
    },
    {
      shift: 'tomas',
      template: 'Station setup and sanitation',
      task: 'Check your station’s product is stocked',
      patch: {
        status: 'skipped',
        reason: 'The shampoo area uses backbar stock, which Riley counts.',
      },
    },
  ],
  handoffs: [
    {
      location: 'pearl',
      author: 'coordinator',
      hoursAgo: 16,
      category: 'inventory',
      urgent: true,
      title: 'Barbicide concentrate is out',
      body: 'Reordered from the supplier, arriving Wednesday. Use disinfectant wipes on tools until then.',
      readBy: ['apprentice'],
    },
    {
      location: 'pearl',
      author: 'stylist-senior',
      hoursAgo: 17,
      category: 'guest',
      title: 'Client unhappy with her fringe length',
      body: 'Offered a free fringe tidy this week. She will call to book. Please be kind at the desk.',
    },
    {
      location: 'pearl',
      author: 'gm-pearl',
      hoursAgo: 3,
      category: 'follow_up',
      title: 'Colour class at 9 AM tomorrow in the back room',
      body: 'Keep the colour bar clear until 10.',
    },
    {
      location: 'pearl',
      author: 'coordinator',
      hoursAgo: 40,
      category: 'maintenance',
      title: 'Dryer 2 is making a grinding noise',
      body: 'Unplugged it and put a note on the door.',
      resolved: {
        by: 'gm-pearl',
        note: 'The landlord’s technician replaced the belt.',
        hoursAgo: 26,
      },
    },
  ],
}

const SEEDS: Record<string, OperationsSeed> = { 'harbor-vine': HARBOR, 'lumen-salon': LUMEN }

// ---------------------------------------------------------------------------

export async function seedOperations(
  db: SeedDb,
  ctx: {
    organizationId: string
    slug: string
    locationIds: Map<string, string>
    locationTimeZones: Map<string, string>
    jobRoleIds: Map<string, string>
    employmentIds: Map<string, string>
    systemEvent: (
      action: string,
      summary: string,
      extra?: Partial<typeof schema.auditEvents.$inferInsert>,
    ) => void
  },
  now = new Date(),
): Promise<{ templates: number; runs: number; handoffs: number }> {
  const seed = SEEDS[ctx.slug]
  if (!seed) return { templates: 0, runs: 0, handoffs: 0 }
  const org = ctx.organizationId
  const person = (key: string) => {
    const id = ctx.employmentIds.get(key)
    if (!id) throw new Error(`Operations seed: unknown person ${key} in ${ctx.slug}`)
    return id
  }
  const place = (key: string) => ctx.locationIds.get(key)!
  const tzOf = (key: string) => ctx.locationTimeZones.get(key)!
  const stationRows = await db
    .select({
      id: schema.stations.id,
      locationId: schema.stations.locationId,
      name: schema.stations.name,
    })
    .from(schema.stations)
    .where(eq(schema.stations.organizationId, org))
  const station = (location: string, name: string) => {
    const row = stationRows.find((s) => s.locationId === place(location) && s.name === name)
    if (!row) throw new Error(`Operations seed: no station ${name} at ${location}`)
    return row.id
  }
  const HOUR = 3_600_000

  // --- templates, published --------------------------------------------------
  const templateIds = new Map<string, string>()
  const taskIds = new Map<string, string>()
  for (const t of seed.templates) {
    const templateId = newId()
    const versionId = newId()
    const publishedAt = new Date(now.getTime() - 9 * 24 * HOUR)
    templateIds.set(t.name, templateId)
    await db.insert(schema.opsTemplates).values({
      id: templateId,
      organizationId: org,
      name: t.name,
      kind: t.kind,
      createdByEmploymentId: person(t.author),
      createdAt: publishedAt,
    })
    await db.insert(schema.opsTemplateVersions).values({
      id: versionId,
      organizationId: org,
      templateId,
      versionNumber: 1,
      name: t.name,
      kind: t.kind,
      description: t.description ?? '',
      createdByEmploymentId: person(t.author),
    })
    for (const location of t.locations) {
      await db
        .insert(schema.opsVersionLocations)
        .values({ id: newId(), organizationId: org, versionId, locationId: place(location) })
    }
    for (const role of t.jobRoles ?? []) {
      await db.insert(schema.opsVersionJobRoles).values({
        id: newId(),
        organizationId: org,
        versionId,
        jobRoleId: ctx.jobRoleIds.get(role)!,
      })
    }
    for (const s of t.stations ?? []) {
      await db.insert(schema.opsVersionStations).values({
        id: newId(),
        organizationId: org,
        versionId,
        stationId: station(s.location, s.name),
      })
    }
    for (const [sectionPosition, section] of t.sections.entries()) {
      const sectionId = newId()
      await db.insert(schema.opsSections).values({
        id: sectionId,
        organizationId: org,
        versionId,
        title: section.title,
        position: sectionPosition,
      })
      for (const [position, task] of section.tasks.entries()) {
        const id = newId()
        taskIds.set(`${t.name}::${task.title}`, id)
        await db.insert(schema.opsTasks).values({
          id,
          organizationId: org,
          versionId,
          sectionId,
          position,
          title: task.title,
          instructions: task.instructions ?? '',
          required: !task.optional,
          responseType: task.response ?? 'check',
          timingAnchor: task.at[0] === 'end' ? 'shift_end' : 'shift_start',
          offsetMinutes: task.at[1],
          requiresVerification: task.verify ?? false,
          shared: task.shared ?? false,
        })
      }
    }
    await db
      .update(schema.opsTemplateVersions)
      .set({ status: 'published', publishedAt, publishedByEmploymentId: person(t.author) })
      .where(eq(schema.opsTemplateVersions.id, versionId))
    await db
      .update(schema.opsTemplates)
      .set({ publishedVersionId: versionId })
      .where(eq(schema.opsTemplates.id, templateId))
    ctx.systemEvent('ops_template.published', `Published version 1 of "${t.name}"`, {
      subjectType: 'ops_template',
      subjectId: templateId,
    })
  }

  // --- today's demo shifts ----------------------------------------------------
  const halfHour = 30 * 60_000
  const shiftIds = new Map<string, string>()
  for (const demo of seed.shifts) {
    const tz = tzOf(demo.location)
    const locationId = place(demo.location)
    let startsAt: Date
    let endsAt: Date
    if (demo.start === 'now') {
      startsAt = new Date(Math.floor(now.getTime() / halfHour) * halfHour - 2 * HOUR)
      endsAt = new Date(startsAt.getTime() + demo.minutes * 60_000)
    } else {
      const today = localDateOf(now, tz)
      startsAt = localTimeToInstant(today, parseTimeOfDay(demo.start)!, tz)!
      endsAt = new Date(startsAt.getTime() + demo.minutes * 60_000)
    }
    const employmentId = person(demo.person)
    const jobRoleId = ctx.jobRoleIds.get(demo.jobRole) ?? null
    const stationId = demo.station ? station(demo.location, demo.station) : null

    const [overlapping] = await db
      .select()
      .from(schema.shifts)
      .where(
        and(
          eq(schema.shifts.organizationId, org),
          eq(schema.shifts.assigneeEmploymentId, employmentId),
          eq(schema.shifts.status, 'active'),
          lt(schema.shifts.startsAt, endsAt),
          gt(schema.shifts.endsAt, startsAt),
        ),
      )
      .limit(1)

    if (overlapping) {
      // Their regular shift today becomes the demo shift, moved to the demo
      // window: nobody is on two shifts at once.
      await db
        .update(schema.shifts)
        .set({
          startsAt,
          endsAt,
          publishedStartsAt: startsAt,
          publishedEndsAt: endsAt,
          jobRoleId,
          stationId,
          publishedJobRoleId: jobRoleId,
          publishedStationId: stationId,
          publishedAssigneeEmploymentId: employmentId,
          publishedStatus: 'active',
          publishedAt: overlapping.publishedAt ?? now,
          publishedBreakMinutes: overlapping.breakMinutes,
          publishedNotes: overlapping.notes,
          publishedIsOpen: false,
        })
        .where(eq(schema.shifts.id, overlapping.id))
      shiftIds.set(demo.key, overlapping.id)
      continue
    }

    const weekStart = weekStartOf(localDateOf(startsAt, tz))
    let [schedule] = await db
      .select({ id: schema.schedules.id })
      .from(schema.schedules)
      .where(
        and(
          eq(schema.schedules.organizationId, org),
          eq(schema.schedules.locationId, locationId),
          eq(schema.schedules.weekStart, weekStart),
        ),
      )
    if (!schedule) {
      schedule = { id: newId() }
      await db.insert(schema.schedules).values({
        id: schedule.id,
        organizationId: org,
        locationId,
        weekStart,
        status: 'published',
        publishedVersion: 1,
        publishedAt: now,
      })
    }
    const id = newId()
    await db.insert(schema.shifts).values({
      id,
      organizationId: org,
      scheduleId: schedule.id,
      locationId,
      jobRoleId,
      stationId,
      startsAt,
      endsAt,
      breakMinutes: 30,
      assigneeEmploymentId: employmentId,
      publishedAt: new Date(now.getTime() - 3 * 24 * HOUR),
      publishedStartsAt: startsAt,
      publishedEndsAt: endsAt,
      publishedBreakMinutes: 30,
      publishedJobRoleId: jobRoleId,
      publishedStationId: stationId,
      publishedNotes: '',
      publishedAssigneeEmploymentId: employmentId,
      publishedIsOpen: false,
      publishedStatus: 'active',
    })
    shiftIds.set(demo.key, id)
  }

  // --- the work, generated exactly as a publish would -------------------------
  // The seed connection is the migration role outside a tenant transaction;
  // the query builder it offers is the same one generation uses.
  const generated = await generateForUpcomingShifts(
    db as unknown as Tx,
    org,
    null,
    null,
    new Date(now.getTime() - 3 * HOUR),
  )

  // --- what people have already done -----------------------------------------
  for (const state of seed.states) {
    const shiftId = shiftIds.get(state.shift)!
    const taskId = taskIds.get(`${state.template}::${state.task}`)
    if (!taskId) throw new Error(`Operations seed: no task "${state.task}" in "${state.template}"`)
    const [item] = await db
      .select()
      .from(schema.opsTaskItems)
      .where(
        and(
          eq(schema.opsTaskItems.organizationId, org),
          eq(schema.opsTaskItems.shiftId, shiftId),
          eq(schema.opsTaskItems.taskId, taskId),
        ),
      )
    if (!item)
      throw new Error(`Operations seed: "${state.task}" was not generated for ${state.shift}`)
    const owner = item.assignedEmploymentId!
    const at = new Date(Math.min(now.getTime() - 4 * 60_000, item.dueAt.getTime() + 2 * 60_000))
    const p = state.patch
    const by = 'by' in p && p.by ? person(p.by) : owner

    let set: Partial<typeof schema.opsTaskItems.$inferInsert>
    let action: 'completed' | 'submitted' | 'skipped' | 'blocked' | 'returned'
    let note = ''
    if (p.status === 'done') {
      set = {
        status: 'done',
        completedByEmploymentId: by,
        completedAt: at,
        responseText: p.text ?? '',
        responseNumber: p.number ?? null,
        verifiedByEmploymentId: p.verifiedBy ? person(p.verifiedBy) : null,
        verifiedAt: p.verifiedBy ? new Date(at.getTime() + 60_000) : null,
      }
      action = 'completed'
    } else if (p.status === 'awaiting_verification') {
      set = {
        status: p.status,
        completedByEmploymentId: by,
        completedAt: at,
        responseText: p.text ?? '',
        responseNumber: p.number ?? null,
      }
      action = 'submitted'
    } else if (p.status === 'skipped') {
      set = { status: 'skipped', completedByEmploymentId: by, completedAt: at, reason: p.reason }
      action = 'skipped'
      note = p.reason
    } else if (p.status === 'blocked') {
      set = { status: 'blocked', reason: p.reason }
      action = 'blocked'
      note = p.reason
    } else {
      set = { status: 'pending', returnedNote: p.returnedNote }
      action = 'returned'
      note = p.returnedNote
    }
    await db
      .update(schema.opsTaskItems)
      .set({ ...set, revision: item.revision + (p.status === 'pending' ? 2 : 1) })
      .where(eq(schema.opsTaskItems.id, item.id))
    if (p.status === 'pending') {
      await db.insert(schema.opsTaskEvents).values({
        id: newId(),
        organizationId: org,
        itemId: item.id,
        runId: item.runId,
        action: 'submitted',
        fromStatus: 'pending',
        toStatus: 'awaiting_verification',
        employmentId: owner,
        at: new Date(at.getTime() - 5 * 60_000),
      })
    }
    await db.insert(schema.opsTaskEvents).values({
      id: newId(),
      organizationId: org,
      itemId: item.id,
      runId: item.runId,
      action,
      fromStatus: p.status === 'pending' ? 'awaiting_verification' : 'pending',
      toStatus: set.status!,
      note,
      employmentId: p.status === 'pending' ? person(p.returnedBy) : by,
      at,
    })
    if ('verifiedBy' in p && p.verifiedBy) {
      await db.insert(schema.opsTaskEvents).values({
        id: newId(),
        organizationId: org,
        itemId: item.id,
        runId: item.runId,
        action: 'verified',
        fromStatus: 'done',
        toStatus: 'done',
        employmentId: person(p.verifiedBy),
        at: new Date(at.getTime() + 60_000),
      })
    }
  }

  // --- handoffs -----------------------------------------------------------------
  for (const h of seed.handoffs) {
    const tz = tzOf(h.location)
    const createdAt = new Date(now.getTime() - h.hoursAgo * HOUR)
    const id = newId()
    await db.insert(schema.handoffs).values({
      id,
      organizationId: org,
      locationId: place(h.location),
      shiftId: h.shift ? shiftIds.get(h.shift)! : null,
      businessDate: localDateOf(createdAt, tz),
      category: h.category,
      priority: h.urgent ? 'urgent' : 'normal',
      title: h.title,
      body: h.body,
      authorEmploymentId: person(h.author),
      status: h.resolved ? 'resolved' : 'open',
      resolvedByEmploymentId: h.resolved ? person(h.resolved.by) : null,
      resolvedAt: h.resolved ? new Date(now.getTime() - h.resolved.hoursAgo * HOUR) : null,
      resolutionNote: h.resolved?.note ?? '',
      createdAt,
      updatedAt: createdAt,
    })
    for (const reader of h.readBy ?? []) {
      await db.insert(schema.handoffAcknowledgements).values({
        id: newId(),
        organizationId: org,
        handoffId: id,
        employmentId: person(reader),
        acknowledgedAt: new Date(createdAt.getTime() + 2 * HOUR),
      })
    }
  }

  return {
    templates: seed.templates.length,
    runs: generated.created,
    handoffs: seed.handoffs.length,
  }
}
